version: '3.1'

services:
  asp.net-demo:
    image: ${DOCKER_REGISTRY-}asp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - web
    labels:
      - traefik.http.routers.api-instance.rule=Host(`${API_URL}`)
      - traefik.port=80
      # - "traefik.http.routers.api-instance.tls=true"
      # - "traefik.http.routers.api-instance.tls.certresolver=lets-encrypt"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    labels:
      - traefik.enable=false
volumes:
  db-data:

networks:
  web:
    external: true